# Taps
tap "railwaycat/emacsmacport"

# Formulae
brew "bat"
brew "cabal-install"
brew "cdrtools"
brew "exiftool"
brew "fd"
brew "findutils"
brew "forgejo-cli"
brew "fzf"
brew "ghc"
brew "git-filter-repo"
brew "gitleaks"
brew "imagemagick"
brew "ispell"
brew "just"
brew "mas"
brew "mediainfo"
brew "mkcert"
brew "mpv"
brew "nmap"
brew "node"
brew "opentofu"
brew "pandoc"
brew "podman"
brew "podman-compose"
brew "poppler"
brew "pre-commit"
brew "resvg"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "skopeo"
brew "sshuttle"
brew "trufflehog"
brew "virt-manager"
brew "wakeonlan"
brew "wget"
brew "yt-dlp"
brew "zsh-autosuggestions"
brew "zsh-completions"

# Casks
cask "balenaetcher"
cask "betterdisplay"
cask "caffeine"
cask "calibre"
cask "claude-code@latest"
cask "claudebar"
cask "discord"
cask "emacs-mac"
cask "font-noto-nerd-font"
cask "iterm2"
cask "jagex"
cask "moonlight"
cask "obsidian"
cask "ollama-app"
cask "onlyoffice"
cask "podman-desktop"
cask "raspberry-pi-imager"
cask "runelite"
cask "signal"
cask "tailscale-app"
cask "ungoogled-chromium"

# Mac App Store
mas "Notability", id: 360593530
mas "Parcel", id: 375589283
mas "Pixelmator Pro", id: 1289583905
mas "Bitwarden", id: 1352778147
mas "Windows App", id: 1295203466
