# Formulae
brew "bat"
brew "block-goose-cli"
brew "cdrtools"
brew "fd"
brew "findutils"
brew "forgejo-cli"
brew "fzf"
brew "git-filter-repo"
brew "gitleaks"
brew "just"
brew "mas"
brew "mkcert"
brew "nmap"
brew "opencode"
brew "pi-coding-agent"
brew "opentofu"
brew "poppler"
brew "resvg"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "trufflehog"
brew "virt-manager"
brew "wakeonlan"
brew "yt-dlp"
brew "zsh-autosuggestions"
brew "zsh-completions"

# Casks
cask "balenaetcher"
cask "betterdisplay"
cask "block-goose"
cask "caffeine"
cask "calibre"
cask "claude-code"
cask "claudebar"
cask "discord"
cask "font-noto-nerd-font"
cask "iina"
cask "iterm2"
cask "jagex"
cask "kitlangton-hex"
cask "lm-studio"
cask "obsidian"
cask "ollama-app"
cask "opencode-desktop"
cask "onlyoffice"
cask "raspberry-pi-imager"
cask "runelite"
cask "signal"
cask "spotify"
cask "steam"
cask "tailscale-app"
cask "ungoogled-chromium"
cask "utm"

# Cursor Extensions
vscode "anthropic.claude-code"
vscode "anysphere.cursorpyright"
vscode "anysphere.remote-ssh"
vscode "keesschollaart.vscode-home-assistant"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-python-envs"
vscode "redhat.ansible"
vscode "redhat.vscode-yaml"
vscode "samuelcolvin.jinjahtml"
vscode "vscodevim.vim"

# Mac App Store
mas "Notability", id: 360593530
mas "Parcel", id: 375589283
mas "Pixelmator Pro", id: 1289583905
mas "Bitwarden", id: 1352778147
mas "Windows App", id: 1295203466
