---
- name: Add direnv hook to zshrc
  ansible.builtin.lineinfile:
    path: "~/.zshrc"
    line: 'eval "$(direnv hook zsh)"'
    create: true
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0644"
- name: Alias cat to bat
  ansible.builtin.lineinfile:
    path: "~/.zshrc"
    regexp: "^alias cat="
    line: "alias cat='bat --style=plain'"
    create: true
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: "0644"
